PS1="\w \$ "
if [ `uname` = Linux ];
then
    alias open="xdg-open"
fi
export RANGER_LOAD_DEFAULT_RC=FALSE
set -o vi
export PATH="$PATH:~/dev-stuff/dot-files/scripts"
alias v="vim"
alias resetbash="source ~/.bashrc"
alias j="~/dev-stuff/terminal-journal/start"
alias jw="~/dev-stuff/terminal-journal/start w"
alias desk="cd ~/Escritorio"
alias dev="cd ~/dev-stuff"
alias cl="clear && ls"
alias p="python3"
alias python="python3"
alias pip="pip3"
alias la="ls -A"
alias clone="git clone"
alias pull="git pull"
alias ch="chmod 0755"
alias ..="cd .."
alias scripts="cd ~/dev-stuff/dot-files/scripts && clear && ls"
alias docs="cd ~/Documentos"
alias e="exit"
alias blog="cd ~/dev-stuff/static-generator"
alias readme="vim README.md"
alias compblog="~/dev-stuff/static-generator/compile"
alias editbash="~/dev-stuff/dot-files/scripts/editbash; source ~/.bashrc"
alias hc="history -c"
alias t="tmux"
alias estudiar="cd ~/dev-stuff/cli-flashcards && ./flashcards"
alias pregunta="cd ~/dev-stuff/cli-flashcards && ./addflashcards"
alias livr="open ~/Documentos/Biblioteca/Medicina"
alias djrunserver="python manage.py runserver"
alias djstartapp="python manage.py startapp"
alias notas="cd ~/notas"
