#!/bin/bash

#   Se necesita crear archivo ~/.alarma
#   Dentro del archivo se necesita establecer las variables:
#       -VOLUMEN
#       -HORA
#       -SONIDO
#       -ACCION

[ $1 = -s ]\
    && { vim ~/.config/alarma/config || touch ~/.config/alarma/config ; exit 0; }

source ~/.alarma
[ `date +%H:%M` = $HORA ]\
    && { $ACCION $VOLUMEN $SONIDO; } \
