#!/bin/bash

OPCION="$1"
[ -l = "$OPCION" ]\
    && { less ~/dev-stuff/dot-files/download-manager-config; exit 0; }
[ -e = "$OPCION" ]\
    && { vim ~/dev-stuff/dot-files/download-manager-config; exit 0; }

function movefiles(){
    FILES=`ls /home/jlrg1992/Descargas | grep "$1-"`
    for f in $FILES
        do
        mv "/home/jlrg1992/Descargas/$f" "$2/$FECHA-$f"
    done
}

FECHA=`date '+%Y-%m-%d-%H-%M'`
while read LINE
    do
    movefiles $LINE
done < ~/dev-stuff/dot-files/download-manager-config
