#!/bin/bash

function convertidor(){
  VIDSSS="${*}"
  AUDSSS="${VIDSSS%%\.*}"
  ffmpeg -i "$VIDSSS" -f mp3 -ab 192000 -vn "$AUDSSS".mp3
}

chmod -x "$@"

for FILESSS in "$@"
  do
    convertidor "$FILESSS"
done

mv *.mp3 ~/Música/2020 && mv * ~/Vídeos/musica
